name: hello branch
on:
  push:
    branches: [dev, stg, prd]
jobs:
  hello-branch:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref_name == 'dev' || github.ref_name == 'n4') && '' || 'approve' }}
    steps:
      - run: echo hello ${{ github.ref_name}}